name: updater

on:
  schedule:
    - cron: '0 12 * * 1' # Runs at 12:00 UTC every Monday

jobs:
  buildV1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/v1'
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env: 
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          YT_CHANNEL_ID: ${{ secrets.YT_CHANNEL_ID }}
          DISCORD_INVITE_ID: ${{ secrets.DISCORD_INVITE_ID }}
        run: python updater.py
          
      - name: check for changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: commit files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Weekly Update" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main